
[functions.finalize-report]
enabled = true
verify_jwt = true
import_map = "./functions/finalize-report/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finalize-report/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finalize-report/*.html" ]

[functions.update-password]
enabled = true
verify_jwt = true
entrypoint = "./functions/update-password/index.ts"

[functions.manage-report-edit]
enabled = true
verify_jwt = true
entrypoint = "./functions/manage-report-edit/index.ts"
